### PR TITLE
Add imgix support for image_downsize

### PR DESCRIPTION
**Pull request by rasmusbe**
image_downsize is used when using get_the_post_thumbnail

### CODE REVIEW

**Comment by thisislawatts** [comment]
Would it be possible to squash these down to a single commit, if it's all tied to `image_downsize`?

**Comment by rasmusbe** [comment]
I also found a problem with `convert_filename_to_size_args` but `image_downsize` makes `convert_filename_to_size_args` unnecessary so we can remove it.

The problem was that if someone uploaded a file with size in filename (for example if you download an resized image from one site to use on this site) the image became broken (since the original file has size attributes which was removed by `convert_filename_to_size_args`.

**Comment by rasmusbe** [comment]
Sure, I'll squash these, just have to fix the tests after my last commit :)

**Comment by thisislawatts** [comment]
Good catch on the filenames containing a size. I hadn't considered that.

**Comment by rasmusbe** [comment]
I have squashed the commits now and made all the tests work.

I removed support for running tests with php 5.5 in travis, it's not supported by php, phpunit nor frozzare/wp-test-suite.

**Comment by rasmusbe** [comment]
Just found a case where `wp_calculate_image_srcset` is still needed 👎 
Will make a fix

**Comment by rasmusbe** [comment]
I have updated it with a fix so it should be ready now

**Comment by rasmusbe** [comment]
ping @thisislawatts

**Pull request merged**
